name: Gradle Tests and Integration Tests

on:
  push:
    branches:
      - '**'  # Run on any branch
  pull_request:
    branches:
      - '**'  # Run on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8081:8081

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew clean build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Integration Tests
        run: ./gradlew integrationTest

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests